### ISSUE TITLE
Bug: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by felipemfp** [lab259/graphqlws-redis#1]
Sometimes I'm experiencing a `panic` using this library:

<pre><font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:10:21Z&quot; level=info msg=&quot;waiting for receiving a message from Redis&quot; connID=ecf0cc09-1d9e-4950-96e2-d817b673133b method=readRedis subscription=1
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=warning msg=&quot;Closing connection&quot; prefix=&quot;graphqlws/connection/ecf0cc09-1d9e-4950-96e2-d817b673133b&quot; reason=&quot;websocket: close 1006 (abnormal closure): unexpected EOF&quot;
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=info msg=&quot;subscription received. Ignoring...&quot; connID=ecf0cc09-1d9e-4950-96e2-d817b673133b method=readRedis subscription=1
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=info msg=&quot;waiting for receiving a message from Redis&quot; connID=ecf0cc09-1d9e-4950-96e2-d817b673133b method=readRedis subscription=1
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=error msg=&quot;error receiving a Redis message&quot; connID=ecf0cc09-1d9e-4950-96e2-d817b673133b error=&quot;redigo: connection closed&quot; method=readRedis subscription=1
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=info msg=&quot;exiting readRedis&quot; connID=ecf0cc09-1d9e-4950-96e2-d817b673133b method=readRedis subscription=1
<font color="#FF79C6">graphql_1          |</font> time=&quot;2019-02-05T18:11:21Z&quot; level=info msg=&quot;Created connection&quot; prefix=&quot;graphqlws/connection/6aee5919-181e-4f60-8739-b27d122e837e&quot;
<font color="#FF79C6">graphql_1          |</font> panic: runtime error: invalid memory address or nil pointer dereference
<font color="#FF79C6">graphql_1          |</font> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x939772]
<font color="#FF79C6">graphql_1          |</font> 
<font color="#FF79C6">graphql_1          |</font> goroutine 3264 [running]:
<font color="#FF79C6">graphql_1          |</font> chatbot/vendor/github.com/lab259/graphqlws-redis.(*redisConnection).ID(0x0, 0xc42045c480, 0xc42045c420)
<font color="#FF79C6">graphql_1          |</font> 	/lab259/chatbot/src/chatbot/vendor/github.com/lab259/graphqlws-redis/connection.go:24 +0x22
<font color="#FF79C6">graphql_1          |</font> chatbot/vendor/github.com/lab259/graphqlws.NewHandler.func2.1(0xd765a0, 0x0, 0xc420288510, 0x1, 0xc42045c420, 0xc42045c420, 0x0, 0x0)
<font color="#FF79C6">graphql_1          |</font> 	/lab259/chatbot/src/chatbot/vendor/github.com/lab259/graphqlws/handler.go:69 +0x19d
<font color="#FF79C6">graphql_1          |</font> chatbot/vendor/github.com/lab259/graphqlws-redis.(*redisConnectionFactory).Create.func3(0xd765e0, 0xc42018e1c0, 0xc420288510, 0x1, 0xc42045c420, 0x0, 0x0, 0xc420922800)
<font color="#FF79C6">graphql_1          |</font> 	/lab259/chatbot/src/chatbot/vendor/github.com/lab259/graphqlws-redis/connection.go:164 +0x6f
<font color="#FF79C6">graphql_1          |</font> chatbot/vendor/github.com/lab259/graphqlws.(*connection).readLoop(0xc42018e1c0)
<font color="#FF79C6">graphql_1          |</font> 	/lab259/chatbot/src/chatbot/vendor/github.com/lab259/graphqlws/connections.go:397 +0x563
<font color="#FF79C6">graphql_1          |</font> created by chatbot/vendor/github.com/lab259/graphqlws.NewConnection
<font color="#FF79C6">graphql_1          |</font> 	/lab259/chatbot/src/chatbot/vendor/github.com/lab259/graphqlws/connections.go:168 +0x1dc
<font color="#FF79C6">graphql_1          |</font> make: *** [Makefile:99: run] Error 2</pre>

See more: [runtime-error-invalid-memory-address.log](https://github.com/lab259/graphqlws-redis/files/2833327/runtime-error-invalid-memory-address.log)

**Comment by chicobentojr** [comment]
[chat-graphql.log](https://github.com/lab259/graphqlws-redis/files/2895648/chat-graphql.log)

I'm facing the same issue
